name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: AutoClicker.sln
      Wix_Project_Path: AutoClicker.Installer/AutoClicker.Installer.wixproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    # Nie trzeba instalować .NET Core osobno - setup-dotnet wystarczy
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Windows-latest ma już WiX, ale warto zaktualizować
    - name: Update WiX
      run: choco upgrade wixtoolset -y

    # Build całego rozwiązania (w tym projektu WiX)
    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=Release /p:Platform="Any CPU"
      

    # Budowa MSI z dokładnym wskazaniem ścieżki
    - name: Build MSI Installer
      run: msbuild "$env:Wix_Project_Path" /p:Configuration=Release /p:WixToolsetPath="C:\Program Files\WiX Toolset v4.0\bin"

    # Weryfikacja wygenerowanych plików
    - name: List MSI Artifacts
      run: Get-ChildItem -Path AutoClicker.Installer/bin/Release -Recurse -Filter *.msi

    # Upload tylko MSI
    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoClicker_Installer
        path: AutoClicker.Installer/bin/Release/*.msi
